spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercedb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


openapi:
  service:
    api-docs: ecommerce-backend-service
    title: Backend API documentation
    version: v1.0.0
    server: http://localhost:${server.port}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
