spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
openapi:
  service:
    title: "Backend API documentation"
    version: "1.0.0"
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}