server:
  port: 8080

spring:
  application:
    name: ecommerce-backend-service
  profiles:
    active: @spring.profiles.active@

#management:
#  endpoint:
#    web:
#      exposure:
#        include: "*"
#
#logging:
#  level:
#    root: info
#    web: info